[package]
name = "operator-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
bincode = "1.3.3"
eyre = "0.6.12"
itertools = "0.14.0"
regex = "1.11.1"
serde = "1.0.218"
tfhe = { version = "*", features = ["boolean", "shortint", "integer"] }
